version: '3'

services:
  express-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./src:/app/src
    environment:
      - PORT=3000
    command: npm run dev