version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  express-app:
    environment:
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
    command: npm run start
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
volumes:
  mongoData: