version: '3'

services:
  express-app:
    image: vamshidev333/node-app
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - PORT=3000
    command: npm run start